# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.BigIntegerField()),
                ('content', models.TextField()),
                ('frequency', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.BigIntegerField()),
                ('response_content', models.CharField(default='No Response', max_length=75)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Habit')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField()),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.Habit')),
            ],
        ),
    ]
